### ISSUE TITLE
Unique solutions?

### ISSUE THREAD

**Issue by ersimont** [grantm/sudoku-exchange-puzzle-bank#1]
Thank you again for this repo! Question: could the puzzles have more than one solution?

I'm using puzzles from here in my own sudoku app, where I have a help item for "Unique Rectangle". And it just occurred to me that could be a bad combination if these are not guaranteed to be unique!

**Comment by grantm** [comment]
The software I used to generate these puzzles definitely checked that they each had a unique solution. I think that the separate software I used to generate the ratings independently checked that too, but I may be wrong.

**Comment by ersimont** [comment]
Great, thanks!

**Comment by barrymichaeldoyle** [comment]
Should probably update that in the docs because I had the same question :)

**Comment by grantm** [comment]
Note added
