### ISSUE TITLE
No isomorph puzzles?

### ISSUE THREAD

**Issue by ersimont** [grantm/sudoku-exchange-puzzle-bank#2]
I got that fancy term "isomorph" from [here](https://sudokugarden.de/en/info/similar).

I wanted to convert all the sudokus in this puzzle bank to a [canonical form](https://sudokugarden.de/en/info/canonical-form). So I did! I thought. But I'm very surprised to see that when converted there are no duplicates. Did you do anything (or did the software you were using automatically do anything) to prevent isomorph sudokus from appearing in the puzzle bank?

**Comment by grantm** [comment]
I also am surprised there are no duplicates 😄  --- I had not taken any steps to avoid that.

The only thing I can think of that I did which might be relevant is that I used the QQWing option to ensure every generated puzzle used some form of symmetry (either rotational or horizontal/vertical mirroring) in the arrangement of the starting digits.  I wonder if that might interact with the canonicalisation in some way.
